[package]
name = "your-language"
version = "0.1.0"
authors = ["Gerrit <gerrit.weiermann@gmx.de>"]
edition = "2018"

[dependencies]
logos = "0.12.0"
node-derive = { path = "./node-derive" }
lazy_static = "1.4.0"
