[package]
name = "your-language"
version = "0.1.0"
authors = ["Gerrit <gerrit.weiermann@gmx.de>"]
edition = "2018"

[dependencies]
#ast = { path = "./ast" }
fsm = { path = "./fsm" }
serde_json = "1.0"
logos = "0.12.0"