[package]
name = "parser"
version = "0.1.0"
authors = ["Gerrit <gerrit.weiermann@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peekmore = "^1.0.0"